# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

spring.application.name=JobApplication
spring.datasource.name=jobman
spring.datasource.url=jdbc:postgresql://localhost:5432/jobman
spring.datasource.password= tester
spring.datasource.username=tester
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.springframework=INFO
spring.jpa.open-in-view=false
logging.level.org.springframework=INFO
spring.jpa.show-sql=true
